services:
  - type: web
    name: cu-staywise
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    repo: https://github.com/projectsbydhruv/CU-StayWise
    autoDeploy: true
